"""Generate charter structural checks from the installed law stack; never edit upstream."""
import argparse
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]/'tests'))
from check_north_america_preflight import ROOT, definitions, fields, one

CHOICES = {
 'governance_principles': ['law_presidential_republic','law_parliamentary_republic'],
 'distribution_of_power': ['law_universal_suffrage','law_census_voting','law_wealth_voting'],
 'economic_system': ['law_interventionism','law_laissez_faire','law_agrarianism'],
}
STRUCTURAL=('disallowing_laws','unlocking_laws','requires_law_or','requires_law_and')


def load_laws(roots):
    files={}
    for root in roots:
        # Reject structural injections; unrelated injected effects do not alter this structural view.
        import json
        meta=root/'.metadata/metadata.json'
        if meta.exists():
            assert not any(str(x).rstrip('/') in ('common','common/laws') for x in json.loads(meta.read_text()).get('replace_paths',[]))
        for p in sorted((root/'common/laws').glob('*.txt')):files[p.name]=p
    laws={}
    for filename,p in sorted(files.items()):
        for raw,block in definitions(p,allow_duplicates=True).items():
            op,sep,key=raw.partition(':')
            if not sep:key=op;op='CREATE'
            assert op in ('CREATE','REPLACE','REPLACE_OR_CREATE','INJECT'),(p,raw)
            # Apply replacement operations after ordinary objects below.
            if op=='CREATE':laws[key]=block
    for filename,p in sorted(files.items()):
        for raw,block in definitions(p,allow_duplicates=True).items():
            if ':' in raw:
                op,key=raw.split(':',1)
                if op=='INJECT':
                    assert not any(fields(block,f) for f in (*STRUCTURAL,'group','parent')), (p,raw)
                    continue
                if op=='REPLACE':assert key in laws,key
                laws[key]=block
    return laws


def render(laws):
    groups={k:one(b,'group').removeprefix('lawgroup_') for k,b in laws.items()}
    def ancestors(k):
        result=[k]
        while fields(laws[k],'parent'):
            k=one(laws[k],'parent');assert k not in result
            result.append(k)
        return result
    def present(k,exact=False):
        group=groups[k];has='has_law' if exact else 'has_law_or_variant'
        if group not in CHOICES:return f'{has} = law_type:{k}'
        var=f'var:ffpa_usa_charter_{group}_v1'
        alts=[f'AND = {{ {var} = 0 {has} = law_type:{k} }}']
        for i,chosen in enumerate(CHOICES[group],1):
            if k==chosen or not exact and k in ancestors(chosen):alts.append(f'{var} = {i}')
        return 'OR = { '+' '.join(alts)+' }'
    rules=[]; reasons=[]; localizations=[]
    for k,b in sorted(laws.items()):
        for field in STRUCTURAL:
            data=[]
            for parent in ancestors(k):
                if fields(laws[parent],field):
                    # Duplicated source lists are conservatively unioned; no removal syntax is used here.
                    data=sorted(set(x for row in fields(laws[parent],field) for x in row));break
            if not data:continue
            if groups[k] not in CHOICES and not any(groups.get(x) in CHOICES for x in data):continue
            assert all(x in laws for x in data),(k,data)
            owner=present(k,True)
            if field=='disallowing_laws':
                condition=' '.join(f'NOT = {{ {present(x)} }}' for x in data)
            else:
                condition=('AND' if field=='requires_law_and' else 'OR')+' = { '+' '.join('AND = { '+present(x)+' }' for x in data)+' }'
            rules.append(f' # {k}: {field}\n trigger_if = {{ limit = {{ {owner} }} {condition} }}')
            key=f'ffpa_usa_charter_rule_{k}_{field}'
            reasons.append(f' text = {{ trigger = {{ {owner} NOT = {{ {condition} }} }} localization_key = {key} }}')
            label=f"[GetLawType('{k}').GetName]"
            targets=', '.join(f"[GetLawType('{x}').GetName]" for x in data)
            en='incompatible with' if field=='disallowing_laws' else 'requires all of' if field=='requires_law_and' else 'requires at least one of'
            zh='不能同时保留' if field=='disallowing_laws' else '须同时具备' if field=='requires_law_and' else '须至少具备一项'
            localizations.append((key,f'{label}{zh}：{targets}。',f'{label} {en}: {targets}.'))
    rules_text = '# Generated by tools/generate_usa_charter_rules.py. Country scope; virtual final laws, no effects.\nffpa_usa_charter_structure_valid_v1 = {\n'+'\n'.join(rules)+'\n}\n'
    custom='ffpa_usa_charter_structure_reason_v1 = {\n type = country\n'+'\n'.join(reasons)+'\n text = { trigger = { always = yes } localization_key = ffpa_usa_charter_structure_ok_v1 }\n}\n'
    outputs={'common/scripted_triggers/ffpa_north_american_charter_rules.txt':rules_text,'common/customizable_localization/ffpa_north_american_charter_rules.txt':custom}
    for lang,index in [('simp_chinese',1),('english',2)]:
        outputs[f'localization/{lang}/ffpa_usa_charter_rules_l_{lang}.yml']='\ufeffl_'+lang+':\n'+''.join(f' {row[0]}: "{row[index]}"\n' for row in localizations)
    return outputs


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--game-root',type=Path,required=True)
    p.add_argument('--upstream',type=Path,action='append',default=[])
    p.add_argument('--check',action='store_true');a=p.parse_args()
    output=render(load_laws([a.game_root,*a.upstream,ROOT]))
    for name,text in output.items():
        dest=ROOT/name
        if a.check:assert dest.read_text()==text, 'Regenerate charter rules after reviewing upstream law changes: '+name
        else:dest.write_text(text)
    print('PASS: generated structural checks and matching bilingual conflict explanations; engine semantics remain untested.')



if __name__=='__main__':main()
