"""Generate the bounded province visitor used by North American agendas.

Source roots are arguments; --check detects stale generated data without writing.
"""
import argparse
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'tests'))
from check_north_america_preflight import ROOT, definitions, one


def province_groups(roots):
    regions = set(one(definitions(roots[-1] / 'common/country_formation/tff_major_formables.txt')['USA'], 'states')) - {'STATE_PUERTO_RICO'}
    files = {}
    for root in roots:
        for path in (root / 'map_data/state_regions').glob('*.txt'):
            files[path.name] = path
    result = {}
    for path in files.values():
        for name, body in definitions(path, allow_duplicates=True).items():
            if name in regions:
                assert name not in result, name
                result[name] = sorted(p.strip('"') for p in one(body, 'provinces'))
    assert result.keys() == regions
    all_provinces = [p for group in result.values() for p in group]
    assert len(all_provinces) == len(set(all_provinces))
    return dict(sorted(result.items()))


def render(groups):
    lines = ['# Generated by tools/generate_north_american_provinces.py; do not hand edit.',
             '# Country scope; only the saved target region runs its province visitor.',
             '# ponytail: static province calls; replace only when a persistent native province iterator is verified.',
             'ffpa_na_union_visit_region_v1 = {']
    for i, (name, provinces) in enumerate(groups.items()):
        lines += [' ' + ('if' if i == 0 else 'else_if') + ' = {',
                  f'  limit = {{ var:ffpa_na_union_region_v1 = s:{name} }}']
        lines += [f'  ffpa_na_union_visit_province_v1 = {{ PROVINCE = {p} }}' for p in provinces]
        lines += [' }']
    return '\n'.join(lines + ['}', ''])


def render_trigger(groups):
    lines = ['# Generated by tools/generate_north_american_provinces.py; do not hand edit.',
             '# Country scope, with the native AI scope:target_state.',
             'ffpa_na_union_is_target_state_v1 = {',
             ' var:ffpa_na_union_status_v1 = 1',
             ' scope:target_state = { NOT = { owner = root } state_region = root.var:ffpa_na_union_region_v1 }']
    for i, (name, provinces) in enumerate(groups.items()):
        lines += [' ' + ('trigger_if' if i == 0 else 'trigger_else_if') + ' = {',
                  f'  limit = {{ var:ffpa_na_union_region_v1 = s:{name} }}', '  OR = {']
        lines += [f'   AND = {{ has_variable = ffpa_na_union_p_{p}_v1 p:{p}.state = scope:target_state }}' for p in provinces]
        lines += ['  }', ' }']
    return '\n'.join(lines + [' trigger_else = { always = no }', '}', ''])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ('game-root', 'techres-root', 'firefall-root'):
        parser.add_argument('--' + name, type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    groups = province_groups((args.game_root, args.techres_root, args.firefall_root))
    for category, output in (('scripted_effects', render(groups)), ('scripted_triggers', render_trigger(groups))):
        target = ROOT / f'common/{category}/ffpa_north_american_union_provinces.txt'
        if args.check:
            assert target.read_text() == output, f'{category} province data is stale; regenerate it.'
        else:
            target.write_text(output)
    print(f'PASS: {len(groups)} regions, {sum(map(len, groups.values()))} provinces; max active scan {max(map(len, groups.values()))}.')


if __name__ == '__main__':
    main()
