"""Generate read-only project views from the actual JE conditions/route whitelists.

Run: python3 tools/generate_cmf_project_widgets.py [--check]
No game state, absolute installation paths, or new periodic scans are generated.
"""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tests'))
from check_north_america_preflight import definitions, fields, one
from check_cmf_presentation import entries


def fmt(block):
    return ' '.join(f'{k} {op} '+('{ '+fmt(v)+' }' if isinstance(v,list) else v) for k,op,v in entries(block))


def outputs():
    result={}
    loc={lang:{} for lang in ('simp_chinese','english')}
    def text(key,zh,en):
        loc['simp_chinese'][key]=zh;loc['english'][key]=en
        return key
    def bilingual(stem):
        for lang,ls in loc.items():
            result[f'localization/{lang}/{stem}_l_{lang}.yml']='\ufeffl_'+lang+':\n'+''.join(f' {k}: "{v}"\n' for k,v in ls.items())
    def colored(key,zh,en):
        text(key+'_yes','#p 达标#!  '+zh,'#p Met#!  '+en)
        text(key+'_no','#n 未达标#!  '+zh,'#n Unmet#!  '+en)
    def decision(condition,key):
        return f'if = {{ limit = {{ {condition} }} custom_tooltip_no_bullet = {key}_yes }} else = {{ custom_tooltip_no_bullet = {key}_no }}'
    header='# Generated by tools/generate_cmf_project_widgets.py; edit source conditions, then regenerate.\n'
    regional=definitions(ROOT/'common/journal_entries/ffpa_imperial_regional_development.txt')
    # Existing data are simple ANDs of state predicates. Fail loudly on new shapes.
    sg=[header];sv=[header];gui=[header,'types ffpa_regional_cmf_widgets {\n'];buildings=set()
    text('ffpa_region_cmf_heading','逐州工程清单','State-by-state construction')
    text('ffpa_region_cmf_entry_heading','开工时领土要求（当前对照）','Territory required at activation (current comparison)')
    text('ffpa_region_cmf_note','领土清单只解释开工条件，不新增维持要求。下方只列实际考核的自有施工州；同一区域的分裂州分别检查，不跨州合并建筑。点击定位图标前往该州。','The territory list explains activation; it adds no ongoing requirement. Only owned state instances assessed for completion appear below. Split states are checked separately; buildings are never pooled across states. Use the location icon to go to a state.')
    text('ffpa_region_cmf_state_met','#p 本州全部达标#!','#p All requirements met in this state#!')
    text('ffpa_region_cmf_state_unmet','#n 本州尚有缺项#!','#n This state has outstanding requirements#!')
    text('ffpa_region_cmf_entry_only','仅开工领土；不列入下方施工考核','Activation territory only; not assessed for construction below')
    for journal,block in regional.items():
        name=journal.removeprefix('je_')+'_cmf_project'
        complete=one(block,'complete');states=fields(complete,'any_scope_state')
        assert len(list(entries(complete)))==len(states)
        regions=[one(s,'state_region') for s in states]
        entry=fields(one(block,'possible'),'owns_entire_state_region')
        sg.append(f'{name}_visible = {{ scope = state is_valid = {{ OR = {{ '+ ' '.join(f'state_region = {s}' for s in regions)+' } } }\n')
        sg.append(f'{name}_entry = {{ scope = country effect = {{\n')
        for region in entry:
            key=f'{name}_entry_{region.lower()}'
            tag=' $ffpa_region_cmf_entry_only$' if 's:'+region not in regions else ''
            colored(key,f'${region}$'+tag,f'${region}$'+tag)
            sg.append(' '+decision('owns_entire_state_region = '+region,key)+'\n')
        for region in regions:
            key=f'{name}_missing_{region[2:].lower()}'
            text(key,f'#n 无自有施工州#!：${region[2:]}$','#n No owned project state#!: $'+region[2:]+'$')
            sg.append(f' if = {{ limit = {{ NOT = {{ any_scope_state = {{ state_region = {region} }} }} }} custom_tooltip_no_bullet = {key} }}\n')
        sg.append('} }\n')
        sg.append(f'{name}_details = {{ scope = state effect = {{\n')
        for state in states:
            region=one(state,'state_region');prefix=name+'_'+region[2:].lower()
            sg.append(f' if = {{ limit = {{ state_region = {region} }}\n')
            sg.append('  if = { limit = { '+fmt(state)+' } custom_tooltip_no_bullet = ffpa_region_cmf_state_met } else = { custom_tooltip_no_bullet = ffpa_region_cmf_state_unmet }\n')
            for key,op,value in entries(state):
                if key=='state_region':continue
                lk=prefix+'_'+key
                if key=='market_access':
                    assert op=='>='
                    colored(lk,f'市场接入：[ROOT.GetState.GetMarketAccess|%1] / 至少{float(value):.0%}',f'Market access: [ROOT.GetState.GetMarketAccess|%1] / at least {float(value):.0%}')
                elif key=='turmoil':
                    assert op=='<'
                    colored(lk,f'动乱：[ROOT.GetState.CalcTurmoil|%1] / 低于{float(value):.0%}',f'Turmoil: [ROOT.GetState.CalcTurmoil|%1] / below {float(value):.0%}')
                elif key=='any_scope_building':
                    kind=one(value,'is_building_type');level=[v for k,o,v in entries(value) if k=='level' and o=='>='];assert len(level)==1 and len(list(entries(value)))==2
                    buildings.add(kind);lk=prefix+'_'+kind
                    current=f"[ROOT.GetState.MakeScope.ScriptValue('ffpa_region_cmf_{kind}_levels')|0]"
                    colored(lk,f'${kind}$：{current}/{level[0]}级',f'${kind}$: {current}/{level[0]} levels')
                else:raise AssertionError((journal,key))
                sg.append('  '+decision(fmt([key,op,value]),lk)+'\n')
            sg.append(' }\n')
        sg.append('} }\n')
        gui.append(f''' type {name} = vbox {{
  spacing = 8
  textbox = {{ text = ffpa_region_cmf_heading autoresize = yes }}
  textbox = {{ text = ffpa_region_cmf_entry_heading autoresize = yes }}
  textbox = {{ text = "[GetScriptedGui('{name}_entry').ExecuteTooltip(GuiScope.SetRoot(JournalEntry.GetCountry.MakeScope).End)]" autoresize = yes multiline = yes max_width = 504 }}
  textbox = {{ text = ffpa_region_cmf_note autoresize = yes multiline = yes max_width = 504 }}
  flowcontainer = {{
   direction = vertical
   spacing = 10
   datamodel = "[JournalEntry.GetCountry.AccessStates]"
   item = {{
    vbox = {{
     visible = "[GetScriptedGui('{name}_visible').IsValid(GuiScope.SetRoot(State.MakeScope).End)]"
     spacing = 4
     hbox = {{
      spacing = 8
      button_icon_goto = {{ size = {{ 26 26 }} tooltip = "ZOOM_TO_STATE" onclick = "[State.ZoomToCapital]" }}
      textbox = {{ text = "[State.GetName]" autoresize = yes }}
     }}
     textbox = {{ text = "[GetScriptedGui('{name}_details').ExecuteTooltip(GuiScope.SetRoot(State.MakeScope).End)]" autoresize = yes multiline = yes max_width = 504 }}
    }}
   }}
  }}
 }}
''')
    for kind in sorted(buildings):
        # any_scope_building checks one building, so report the maximum level,
        # not a sum of distinct building instances that could falsely meet it.
        sv.append(f'ffpa_region_cmf_{kind}_levels = {{ value = 0 every_scope_building = {{ limit = {{ is_building_type = {kind} }} min = this.level }} }}\n')
    gui.append('}\n')
    for journal in regional:
        name=journal.removeprefix('je_')+'_cmf_project';gui.append(f'{name} = {{ name = "{name}" }}\n')
    result['common/scripted_guis/ffpa_regional_development_cmf.txt']=''.join(sg)
    result['common/script_values/ffpa_regional_development_cmf.txt']=''.join(sv)
    result['gui/ffpa_regional_development_cmf.gui']=''.join(gui)
    bilingual('ffpa_regional_development_cmf')

    # North America is independent. Fixed rows come from the route whitelist;
    # each is evaluated against the live target state, never a cached building.
    loc={lang:{} for lang in ('simp_chinese','english')}
    text('ffpa_na_cmf_project_heading','当前工程与建筑','Current project and buildings')
    text('ffpa_na_cmf_project_note','只统计已选方向、已建成且就业达到60%的建筑等级；建设队列不计入。每类建筑分别判定就业，再累加合格等级。点击建筑旁的定位图标打开其详情。','Only completed levels in the selected route with at least 60% employment count. Queued construction is excluded. Employment is checked per building before qualifying levels are added. Use the icon beside a building to open its details.')
    text('ffpa_na_cmf_building_missing','未建成：0级；贡献0级','Not built: 0 levels; contributes 0')
    text('ffpa_na_cmf_building_empty','当前没有已建成等级；贡献0级','No completed levels; contributes 0')
    text('ffpa_na_cmf_project_route',"工程方向：[JournalEntry.GetCountry.GetCustom('ffpa_na_local_route_name_v1')]","Route: [JournalEntry.GetCountry.GetCustom('ffpa_na_local_route_name_v1')]")
    text('ffpa_na_cmf_project_ready',"#p 就业达标#!  已建成[Building.MakeScope.ScriptValue('ffpa_na_cmf_completed_levels')|0]级；就业[Building.GetEmploymentPercentage|%1]；贡献[Building.MakeScope.ScriptValue('ffpa_na_cmf_completed_levels')|0]级","#p Employment met#!  [Building.MakeScope.ScriptValue('ffpa_na_cmf_completed_levels')|0] completed levels; employment [Building.GetEmploymentPercentage|%1]; contributes [Building.MakeScope.ScriptValue('ffpa_na_cmf_completed_levels')|0] levels")
    text('ffpa_na_cmf_project_understaffed',"#n 就业不足#!  已建成[Building.MakeScope.ScriptValue('ffpa_na_cmf_completed_levels')|0]级；就业[Building.GetEmploymentPercentage|%1]；贡献0级","#n Understaffed#!  [Building.MakeScope.ScriptValue('ffpa_na_cmf_completed_levels')|0] completed levels; employment [Building.GetEmploymentPercentage|%1]; contributes 0")
    sg=[header,'''ffpa_na_cmf_target_visible = { scope = country is_valid = { ffpa_na_local_target_valid_v1 = yes } }
ffpa_na_cmf_building_staffed = { scope = building is_valid = { level > 0 occupancy >= 0.60 } }
ffpa_na_cmf_building_completed = { scope = building is_valid = { level > 0 } }
''']
    gui=[header,'''types ffpa_na_cmf_project_widgets {
 type ffpa_na_cmf_project = vbox {
  spacing = 8
  textbox = { text = ffpa_na_cmf_project_heading autoresize = yes }
  textbox = { text = ffpa_na_cmf_project_route autoresize = yes multiline = yes max_width = 504 }
  textbox = { text = "[JournalEntry.GetCountry.GetCustom('ffpa_na_cmf_forecast')]" autoresize = yes multiline = yes max_width = 504 }
  container = {
   visible = "[GetScriptedGui('ffpa_na_cmf_target_visible').IsValid(GuiScope.SetRoot(JournalEntry.GetCountry.MakeScope).End)]"
   datacontext = "[JournalEntry.GetCountry.MakeScope.Var('ffpa_na_local_target_v1').GetState]"
   vbox = {
    spacing = 6
    hbox = {
     spacing = 8
     button_icon_goto = { size = { 26 26 } tooltip = "ZOOM_TO_STATE" onclick = "[State.ZoomToCapital]" }
     textbox = { text = "[State.GetName]" autoresize = yes }
    }
    textbox = { text = "[JournalEntry.GetCountry.GetCustom('ffpa_na_cmf_target_details')]" autoresize = yes multiline = yes max_width = 504 }
    textbox = { text = ffpa_na_cmf_project_note autoresize = yes multiline = yes max_width = 504 }
''']
    routes=definitions(ROOT/'common/scripted_triggers/ffpa_north_american_triggers.txt')
    for route in range(1,4):
        sg.append(f'ffpa_na_cmf_route_{route}_visible = {{ scope = country is_valid = {{ ffpa_na_local_target_valid_v1 = yes has_variable = ffpa_na_local_route_v1 var:ffpa_na_local_route_v1 = {route} }} }}\n')
        gui.append(f'''    vbox = {{
     spacing = 6
     visible = "[GetScriptedGui('ffpa_na_cmf_route_{route}_visible').IsValid(GuiScope.SetRoot(JournalEntry.GetCountry.MakeScope).End)]"
''')
        kinds=fields(one(routes[f'ffpa_na_local_building_{route}_v1'],'OR'),'is_building_type')
        assert kinds
        for kind in kinds:
            gui.append(f'''     vbox = {{
      spacing = 3
      textbox = {{ text = {kind} autoresize = yes }}
      textbox = {{ visible = "[Not(State.GetBuilding('{kind}').IsValid)]" text = ffpa_na_cmf_building_missing autoresize = yes }}
      container = {{
       visible = "[State.GetBuilding('{kind}').IsValid]"
       datacontext = "[State.GetBuilding('{kind}')]"
       hbox = {{
        spacing = 6
        button_icon_goto = {{ size = {{ 26 26 }} tooltip = "[Building.GetName]" onclick = "[InformationPanelBar.OpenBuildingDetailsPanel(Building.AccessSelf)]" }}
        vbox = {{
         textbox = {{ visible = "[GetScriptedGui('ffpa_na_cmf_building_staffed').IsValid(GuiScope.SetRoot(Building.MakeScope).End)]" text = ffpa_na_cmf_project_ready autoresize = yes multiline = yes max_width = 468 }}
         textbox = {{ visible = "[And(GetScriptedGui('ffpa_na_cmf_building_completed').IsValid(GuiScope.SetRoot(Building.MakeScope).End), Not(GetScriptedGui('ffpa_na_cmf_building_staffed').IsValid(GuiScope.SetRoot(Building.MakeScope).End)))]" text = ffpa_na_cmf_project_understaffed autoresize = yes multiline = yes max_width = 468 }}
         textbox = {{ visible = "[Not(GetScriptedGui('ffpa_na_cmf_building_completed').IsValid(GuiScope.SetRoot(Building.MakeScope).End))]" text = ffpa_na_cmf_building_empty autoresize = yes }}
        }}
       }}
      }}
     }}
''')
        gui.append('    }\n')
    gui.append('   }\n  }\n }\n}\nffpa_na_cmf_project = { name = "ffpa_na_cmf_project" }\n')
    result['gui/ffpa_north_american_cmf.gui']=''.join(gui)
    result['common/scripted_guis/ffpa_north_american_cmf.txt']=''.join(sg)
    result['common/script_values/ffpa_north_american_cmf.txt']=header+'# Building scope: native completed level accessor, excluding the queue.\nffpa_na_cmf_completed_levels = { value = 0 add = this.level }\n'
    bilingual('ffpa_north_american_projects_cmf')
    return result


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');args=p.parse_args()
    generated=outputs()
    for name,content in generated.items():
        target=ROOT/name
        if args.check:
            assert target.exists() and target.read_text()==content, f'Outdated {name}; regenerate project widgets'
        else:
            target.parent.mkdir(parents=True,exist_ok=True);target.write_text(content)
    print(f'PASS: {len(generated)} project view files '+('match source conditions' if args.check else 'generated'))


if __name__=='__main__':main()
